name: Update Coding Progress

on:
  workflow_dispatch:

jobs:
  update-progress:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update progress
        run: echo "Coding progress updated on $(date)" >> progress.txt

      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add progress.txt
          git commit -m "Update coding progress [skip ci]" || echo "No changes to commit"
          git push
